// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnbdglRND1FAGzHYpoy6ca1GAq0khyn1M',
    appId: '1:796966176613:web:9579f2ce47d3393e6d438c',
    messagingSenderId: '796966176613',
    projectId: 'blogprectice',
    authDomain: 'blogprectice.firebaseapp.com',
    storageBucket: 'blogprectice.firebasestorage.app',
    measurementId: 'G-7HQ3PESCZD',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0550DPhz0isrUvHEryYkAbx48GxiACcE',
    appId: '1:796966176613:ios:7dd46c9e5d9edb266d438c',
    messagingSenderId: '796966176613',
    projectId: 'blogprectice',
    storageBucket: 'blogprectice.firebasestorage.app',
    iosBundleId: 'com.example.precticeBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnbdglRND1FAGzHYpoy6ca1GAq0khyn1M',
    appId: '1:796966176613:web:34c808ea0272571d6d438c',
    messagingSenderId: '796966176613',
    projectId: 'blogprectice',
    authDomain: 'blogprectice.firebaseapp.com',
    storageBucket: 'blogprectice.firebasestorage.app',
    measurementId: 'G-J1K953X4B1',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AMX7zf606peHSF8DbdqEheZ_3_-rqfM',
    appId: '1:796966176613:android:cd3cbf05c071443c6d438c',
    messagingSenderId: '796966176613',
    projectId: 'blogprectice',
    storageBucket: 'blogprectice.firebasestorage.app',
  );
}
